spring:
  application:
    name: eureka-service

server:
  port: 8302

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

zuul:
  prefix: /api
  routes:
      db-service:
        path: /db-service/**
        url: http://localhost:8053
      stock-service:
        path: /stock-service/**
        url: http://localhost:8301